spring:
  thymeleaf:
    cache: false
  cassandra:
    port: 9042
    keyspace-name: tacocloud
    schema-action: recreate
    local-datacenter: datacenter1
    # username: tacocloud
    # password: password